tasks:
- init: >
    bash ./downloadExtensions.sh &&
    (cd 4.2.0 && yarn) &&
    (cd 4.2.1 && yarn)
  command: >
    (cd 4.2.0 && time node index.js | tee 4.2.0.txt) &&
    (cd 4.2.1 && time node index.js | tee 4.2.1.txt)
