wget https://open-vsx.org/api/vscode/bat/1.44.2/file/vscode.bat-1.44.2.vsix
wget https://open-vsx.org/api/vscode/clojure/1.44.2/file/vscode.clojure-1.44.2.vsix
wget https://open-vsx.org/api/vscode/coffeescript/1.44.2/file/vscode.coffeescript-1.44.2.vsix
wget https://open-vsx.org/api/vscode/configuration-editing/1.44.2/file/vscode.configuration-editing-1.44.2.vsix
wget https://open-vsx.org/api/vscode/cpp/1.44.2/file/vscode.cpp-1.44.2.vsix
wget https://open-vsx.org/api/vscode/csharp/1.44.2/file/vscode.csharp-1.44.2.vsix
wget https://open-vsx.org/api/vscode/css/1.44.2/file/vscode.css-1.44.2.vsix
wget https://open-vsx.org/api/vscode/css-language-features/1.45.1/file/vscode.css-language-features-1.45.1.vsix
wget https://open-vsx.org/api/vscode/debug-auto-launch/1.44.2/file/vscode.debug-auto-launch-1.44.2.vsix
wget https://open-vsx.org/api/vscode/docker/1.44.2/file/vscode.docker-1.44.2.vsix
wget https://open-vsx.org/api/vscode/emmet/1.44.2/file/vscode.emmet-1.44.2.vsix
wget https://open-vsx.org/api/vscode/fsharp/1.44.2/file/vscode.fsharp-1.44.2.vsix
wget https://open-vsx.org/api/vscode/go/1.44.2/file/vscode.go-1.44.2.vsix
wget https://open-vsx.org/api/vscode/groovy/1.44.2/file/vscode.groovy-1.44.2.vsix
wget https://open-vsx.org/api/vscode/grunt/1.44.2/file/vscode.grunt-1.44.2.vsix
wget https://open-vsx.org/api/vscode/gulp/1.44.2/file/vscode.gulp-1.44.2.vsix
wget https://open-vsx.org/api/vscode/handlebars/1.44.2/file/vscode.handlebars-1.44.2.vsix
wget https://open-vsx.org/api/vscode/hlsl/1.44.2/file/vscode.hlsl-1.44.2.vsix
wget https://open-vsx.org/api/vscode/html/1.48.0-next.4a1bcdafe9/file/vscode.html-1.48.0-next.4a1bcdafe9.vsix
wget https://open-vsx.org/api/vscode/html-language-features/1.48.0-next.4a1bcdafe9/file/vscode.html-language-features-1.48.0-next.4a1bcdafe9.vsix
wget https://open-vsx.org/api/vscode/ini/1.44.2/file/vscode.ini-1.44.2.vsix
wget https://open-vsx.org/api/vscode/jake/1.44.2/file/vscode.jake-1.44.2.vsix
wget https://open-vsx.org/api/vscode/java/1.44.2/file/vscode.java-1.44.2.vsix
wget https://open-vsx.org/api/vscode/javascript/1.44.2/file/vscode.javascript-1.44.2.vsix
wget https://open-vsx.org/api/vscode/json/1.46.1/file/vscode.json-1.46.1.vsix
wget https://open-vsx.org/api/vscode/json-language-features/1.46.1/file/vscode.json-language-features-1.46.1.vsix
wget https://open-vsx.org/api/vscode/less/1.44.2/file/vscode.less-1.44.2.vsix
wget https://open-vsx.org/api/vscode/log/1.44.2/file/vscode.log-1.44.2.vsix
wget https://open-vsx.org/api/vscode/lua/1.44.2/file/vscode.lua-1.44.2.vsix
wget https://open-vsx.org/api/vscode/make/1.44.2/file/vscode.make-1.44.2.vsix
wget https://open-vsx.org/api/vscode/markdown/1.44.2/file/vscode.markdown-1.44.2.vsix
wget https://open-vsx.org/api/vscode/markdown-language-features/1.39.1/file/vscode.markdown-language-features-1.39.1.vsix
wget https://open-vsx.org/api/vscode/merge-conflict/1.44.2/file/vscode.merge-conflict-1.44.2.vsix
wget https://open-vsx.org/api/vscode/npm/1.44.2/file/vscode.npm-1.44.2.vsix
wget https://github.com/theia-ide/vscode-node-debug/releases/download/v1.35.3/node-debug-1.35.3.vsix
wget https://open-vsx.org/api/ms-vscode/node-debug2/1.33.0/file/ms-vscode.node-debug2-1.33.0.vsix
wget https://open-vsx.org/api/vscode/objective-c/1.44.2/file/vscode.objective-c-1.44.2.vsix
wget https://open-vsx.org/api/vscode/perl/1.44.2/file/vscode.perl-1.44.2.vsix
wget https://open-vsx.org/api/vscode/powershell/1.44.2/file/vscode.powershell-1.44.2.vsix
wget https://open-vsx.org/api/vscode/pug/1.44.2/file/vscode.pug-1.44.2.vsix
wget https://open-vsx.org/api/vscode/python/1.44.2/file/vscode.python-1.44.2.vsix
wget https://open-vsx.org/api/vscode/r/1.44.2/file/vscode.r-1.44.2.vsix
wget https://open-vsx.org/api/vscode/razor/1.44.2/file/vscode.razor-1.44.2.vsix
wget https://open-vsx.org/api/vscode/ruby/1.44.2/file/vscode.ruby-1.44.2.vsix
wget https://open-vsx.org/api/vscode/rust/1.44.2/file/vscode.rust-1.44.2.vsix
wget https://open-vsx.org/api/vscode/scss/1.44.2/file/vscode.scss-1.44.2.vsix
wget https://open-vsx.org/api/vscode/shaderlab/1.44.2/file/vscode.shaderlab-1.44.2.vsix
wget https://open-vsx.org/api/vscode/shellscript/1.44.2/file/vscode.shellscript-1.44.2.vsix
wget https://open-vsx.org/api/vscode/sql/1.44.2/file/vscode.sql-1.44.2.vsix
wget https://open-vsx.org/api/vscode/swift/1.44.2/file/vscode.swift-1.44.2.vsix
wget https://open-vsx.org/api/vscode/theme-abyss/1.44.2/file/vscode.theme-abyss-1.44.2.vsix
wget https://open-vsx.org/api/vscode/theme-defaults/1.44.2/file/vscode.theme-defaults-1.44.2.vsix
wget https://open-vsx.org/api/vscode/theme-kimbie-dark/1.44.2/file/vscode.theme-kimbie-dark-1.44.2.vsix
wget https://open-vsx.org/api/vscode/theme-monokai/1.44.2/file/vscode.theme-monokai-1.44.2.vsix
wget https://open-vsx.org/api/vscode/theme-monokai-dimmed/1.44.2/file/vscode.theme-monokai-dimmed-1.44.2.vsix
wget https://open-vsx.org/api/vscode/theme-quietlight/1.44.2/file/vscode.theme-quietlight-1.44.2.vsix
wget https://open-vsx.org/api/vscode/theme-red/1.44.2/file/vscode.theme-red-1.44.2.vsix
wget https://open-vsx.org/api/vscode/theme-solarized-dark/1.44.2/file/vscode.theme-solarized-dark-1.44.2.vsix
wget https://open-vsx.org/api/vscode/theme-tomorrow-night-blue/1.44.2/file/vscode.theme-tomorrow-night-blue-1.44.2.vsix
wget https://open-vsx.org/api/vscode/typescript/1.44.2/file/vscode.typescript-1.44.2.vsix
wget https://open-vsx.org/api/vscode/typescript-language-features/1.44.2/file/vscode.typescript-language-features-1.44.2.vsix
wget https://open-vsx.org/api/vscode/vb/1.44.2/file/vscode.vb-1.44.2.vsix
wget https://open-vsx.org/api/vscode/vscode-theme-seti/1.44.2/file/vscode.vscode-theme-seti-1.44.2.vsix
wget https://open-vsx.org/api/vscode/xml/1.44.2/file/vscode.xml-1.44.2.vsix
wget https://open-vsx.org/api/vscode/yaml/1.44.2/file/vscode.yaml-1.44.2.vsix
wget https://open-vsx.org/api/EditorConfig/EditorConfig/0.14.4/file/EditorConfig.EditorConfig-0.14.4.vsix
wget https://open-vsx.org/api/dbaeumer/vscode-eslint/2.1.1/file/dbaeumer.vscode-eslint-2.1.1.vsix
wget https://open-vsx.org/api/ms-vscode/references-view/0.0.47/file/ms-vscode.references-view-0.0.47.vsix

# Bonus: two of the biggest extensions (not in main repo example app)
wget https://github.com/redhat-developer/vscode-java/releases/download/v0.54.2/redhat.java-0.54.2.vsix
wget https://github.com/microsoft/vscode-python/releases/download/2020.1.58038/ms-python-release.vsix